import type { Designer, Manager } from "./schema";

export const demoManager: Manager = {
  id: "demo-manager-amelia",
  name: "Amelia Chen",
  avatarColor: "avatar:aurora",
};

export const demoDesigners: Designer[] = [
  {
    id: "demo-designer-maya",
    managerId: demoManager.id,
    name: "Maya Patel",
    level: "Lead Designer",
    maturityInRole: 5,
    fitForRole: 4,
    archetype: "Strategy",
    skills: {
      "Product Thinking": 5,
      "Visual & UI Craft": 4,
      "UX & Interaction Design": 5,
      "Design Systems": 3,
      "Storytelling & Influence": 5,
      "Data-Informed Decisions": 4,
      "Research & Discovery": 4,
      "Prototyping & Experimentation": 4,
      "AI-Augmented Design": 4,
      "Leadership & Collaboration": 5,
    },
  },
  {
    id: "demo-designer-eli",
    managerId: demoManager.id,
    name: "Eli Morgan",
    level: "Senior Designer",
    maturityInRole: 4,
    fitForRole: 5,
    archetype: "Craft",
    skills: {
      "Product Thinking": 4,
      "Visual & UI Craft": 5,
      "UX & Interaction Design": 4,
      "Design Systems": 4,
      "Storytelling & Influence": 4,
      "Data-Informed Decisions": 3,
      "Research & Discovery": 3,
      "Prototyping & Experimentation": 5,
      "AI-Augmented Design": 4,
      "Leadership & Collaboration": 4,
    },
  },
  {
    id: "demo-designer-nora",
    managerId: demoManager.id,
    name: "Nora Singh",
    level: "Staff Designer",
    maturityInRole: 4,
    fitForRole: 4,
    archetype: "Systems",
    skills: {
      "Product Thinking": 4,
      "Visual & UI Craft": 4,
      "UX & Interaction Design": 4,
      "Design Systems": 5,
      "Storytelling & Influence": 4,
      "Data-Informed Decisions": 4,
      "Research & Discovery": 3,
      "Prototyping & Experimentation": 3,
      "AI-Augmented Design": 5,
      "Leadership & Collaboration": 5,
    },
  },
  {
    id: "demo-designer-jules",
    managerId: demoManager.id,
    name: "Jules Rivera",
    level: "Midweight Designer",
    maturityInRole: 3,
    fitForRole: 3,
    archetype: "Craft",
    skills: {
      "Product Thinking": 3,
      "Visual & UI Craft": 4,
      "UX & Interaction Design": 4,
      "Design Systems": 3,
      "Storytelling & Influence": 3,
      "Data-Informed Decisions": 3,
      "Research & Discovery": 4,
      "Prototyping & Experimentation": 4,
      "AI-Augmented Design": 3,
      "Leadership & Collaboration": 3,
    },
  },
  {
    id: "demo-designer-sam",
    managerId: demoManager.id,
    name: "Sam Okafor",
    level: "Associate Designer",
    maturityInRole: 2,
    fitForRole: 4,
    archetype: "Systems",
    skills: {
      "Product Thinking": 3,
      "Visual & UI Craft": 3,
      "UX & Interaction Design": 3,
      "Design Systems": 4,
      "Storytelling & Influence": 2,
      "Data-Informed Decisions": 3,
      "Research & Discovery": 3,
      "Prototyping & Experimentation": 3,
      "AI-Augmented Design": 4,
      "Leadership & Collaboration": 3,
    },
  },
];
